version: '3'
services:
  redis:
    image: 'redis:alpine'
    command: redis-server --requirepass qsef7421
    expose:
      - '6379'
    volumes:
      - ./.cache/redis:/data
    ports:
      - '6379:6379'
  database:
    image: 'postgres:13'
    environment:
      - POSTGRES_USER=jason
      - POSTGRES_PASSWORD=qsef7421
      - POSTGRES_DB=jasonsilvers_db
    ports:
      - '5432:5432'